; Test structure primitives
(⊙≔ (⌜ :Point) (⌜ :x) (⌜ :y))
(≔ p (⊙ (⌜ :Point) #3 #4))
(⟲ p)
(⊢ (≡ (⊙→ p (⌜ :x)) #3) (⌜ :test-point-x))
(⊢ (≡ (⊙→ p (⌜ :y)) #4) (⌜ :test-point-y))
(⊙≔ (⌜ :Rectangle) (⌜ :width) (⌜ :height) (⌜ :color))
(≔ r (⊙ (⌜ :Rectangle) #10 #20 (⌜ :red)))
(⊢ (≡ (⊙→ r (⌜ :width)) #10) (⌜ :test-rect-width))
(⊢ (≡ (⊙→ r (⌜ :height)) #20) (⌜ :test-rect-height))
(⊢ (≡ (⊙→ r (⌜ :color)) (⌜ :red)) (⌜ :test-rect-color))
(⟲ (⌜ :all-tests-passed))
